digit:
	gcc 0-quinINTusar.c
	./a.out
output:
	gcc 1-output.c
	./a.out
input:
	gcc 2-input.c
	./a.out < loli
	cat loli
mutacio:
	gcc 3-mutacions.c
	./a.out

magiaNegra:
	gcc lib16Fitxes.c 4-magiaNegra.c --debug
	./a.out
